-- Resume Database Schema
-- Generated by admin.html on 2026-10-04

-- Drop existing tables if they exist
DROP TABLE IF EXISTS education;
DROP TABLE IF EXISTS career;
DROP TABLE IF EXISTS skills;
DROP TABLE IF EXISTS languages;

-- Education table
CREATE TABLE IF NOT EXISTS education (
    id INTEGER PRIMARY KEY,
    graduation_year TEXT,
    institution TEXT,
    degree TEXT,
    description TEXT
);

-- Career table
CREATE TABLE IF NOT EXISTS career (
    id INTEGER PRIMARY KEY,
    date_range TEXT,
    company TEXT,
    position TEXT,
    location TEXT
);

-- Skills table
CREATE TABLE IF NOT EXISTS skills (
    id INTEGER PRIMARY KEY,
    name TEXT,
    percentage INTEGER,
    description TEXT
);

-- Language skills table
CREATE TABLE IF NOT EXISTS languages (
    id INTEGER PRIMARY KEY,
    name TEXT,
    percentage INTEGER
);

-- Insert Education Data
INSERT INTO education (graduation_year, institution, degree, description) VALUES
('Graduated 2017', 'Tokyo University of Technology', 'Bachelor of Computer Science', 'System Engineering'),
('Graduated 2012', 'College of Technology at Albaha', 'Diploma of Computer Technology', 'Computer Programming');

-- Insert Career Data
INSERT INTO career (date_range, company, position, location) VALUES
('May 2019 - July 2022', 'specialized by stc', 'IT Application Engineer (May 2019 - May 2021) | IT Application Specialist May (2021 - July 2022)', ''),
('July 2022 - Present', 'iotsquared', 'Senior Applications & Analytics Specialist', 'Riyadh, Saudi Arabia');

-- Insert Skills Data
INSERT INTO skills (name, percentage, description) VALUES
('Programming', 90, 'Dedicated software developer with over a decade of experience, starting in 2012 with Java-based Windows applications. Continuously committed to learning and adapting to new technologies, I have mastered modern frontend and backend frameworks, as well as cloud platforms such as Alibaba Cloud and Google Cloud. Skilled in DevOps practices, with hands-on experience building and optimizing CI/CD pipelines using Jenkins. Proven ability to deliver robust, scalable solutions across diverse tech stacks.'),
('UI/UX DESIGN', 95, 'Detail-oriented UI/UX designer with a strong focus on user-centered design principles. Adept at crafting intuitive, visually compelling interfaces that balance functionality with aesthetics. Experienced in translating user needs into seamless digital experiences through wireframing, prototyping, and usability testing. Passionate about staying current with design trends and emerging tools to drive innovation and enhance product usability.'),
('Microcontroller & Embedded Systems', 60, 'Proficient in embedded systems development with hands-on experience in FreeRTOS, Zephyr OS, and low-level programming for microcontrollers. Skilled in integrating hardware and software to enable efficient communication between embedded devices and connectivity modules. Solid understanding of real-time systems and IoT protocols, with a proven track record of delivering reliable, performance-driven embedded solutions.'),
('Renewable Energy (Emerging Interest)', 15, 'Currently expanding knowledge in renewable energy technologies, with foundational experience in green hydrogen generation and solar power systems. Actively pursuing opportunities to contribute to sustainable energy projects and grow expertise in the field.');

-- Insert Language Skills Data
INSERT INTO languages (name, percentage) VALUES
('Japanese LANGUAGE', 90),
('ENGLISH LANGUAGE', 65);
