-- Resume Database Schema
-- Generated by admin.html on 2026-10-04

-- Drop existing tables if they exist
DROP TABLE IF EXISTS works;
DROP TABLE IF EXISTS education;
DROP TABLE IF EXISTS career;
DROP TABLE IF EXISTS skills;
DROP TABLE IF EXISTS languages;

-- Works (portfolio projects) table
CREATE TABLE IF NOT EXISTS works (
    id INTEGER PRIMARY KEY,
    title TEXT,
    category TEXT,
    year TEXT,
    role TEXT,
    image TEXT,
    summary TEXT,
    description TEXT,
    tech TEXT,
    live_url TEXT,
    repo_url TEXT
);

-- Education table
CREATE TABLE IF NOT EXISTS education (
    id INTEGER PRIMARY KEY,
    graduation_year TEXT,
    institution TEXT,
    degree TEXT,
    description TEXT
);

-- Career table
CREATE TABLE IF NOT EXISTS career (
    id INTEGER PRIMARY KEY,
    date_range TEXT,
    company TEXT,
    position TEXT,
    location TEXT
);

-- Skills table
CREATE TABLE IF NOT EXISTS skills (
    id INTEGER PRIMARY KEY,
    name TEXT,
    percentage INTEGER,
    description TEXT
);

-- Language skills table
CREATE TABLE IF NOT EXISTS languages (
    id INTEGER PRIMARY KEY,
    name TEXT,
    percentage INTEGER
);

-- Insert Works Data
INSERT INTO works (title, category, year, role, image, summary, description, tech, live_url, repo_url) VALUES
('FleetPulse — IoT Telemetry Platform', 'IoT', '2025', 'Lead full-stack engineer', 'image/works/fleetpulse.svg', 'A live operations dashboard streaming data from thousands of connected sensors, with alerting and analytics built in.', 'FleetPulse gives operations teams a single, real-time view of every connected device in the field. Sensor data arrives over MQTT, is stored in a time-series database and is pushed to the browser within a second.

I designed the data pipeline and the dashboard end to end: device onboarding, live charts, a geographic view of active units and a rules engine that raises alerts when readings drift outside safe ranges.

The result: faster incident response, fewer site visits and one shared source of truth for engineering and business teams.', 'React, Node.js, MQTT, TimescaleDB, Docker', '', ''),
('Sakura Lingo — Japanese Learning App', 'Mobile', '2024', 'Product designer & developer', 'image/works/sakura-lingo.svg', 'A bite-sized Japanese course with kana drills, spaced repetition and JLPT-style quizzes.', 'Drawing on five years of living in Japan and my experience teaching the language, Sakura Lingo turns the first steps of learning Japanese into a daily five-minute habit.

Learners practise hiragana and katakana with handwriting-friendly drills, review vocabulary with spaced repetition and track their readiness for each JLPT level.

I handled the full product, from user research and Figma prototypes to the Flutter app and its Firebase backend.', 'Flutter, Firebase, Figma', '', ''),
('Edge Sensor Node Firmware', 'Embedded', '2024', 'Firmware engineer', 'image/works/edge-node.svg', 'Low-power environmental sensor firmware on Zephyr RTOS with BLE provisioning and secure over-the-air updates.', 'A battery-powered sensor node designed to run for years in the field. The firmware samples temperature, humidity and air quality, then batches readings over LoRaWAN to save power.

Key work included a BLE provisioning flow for installers, a signed OTA update pipeline and careful power profiling that brought sleep current down to the microamp range.', 'C, Zephyr RTOS, nRF52840, BLE, LoRaWAN', '', ''),
('Insight — Analytics Workspace', 'Web App', '2023', 'Applications & analytics specialist', 'image/works/insight.svg', 'A self-service analytics portal that turns operational data into dashboards business teams can use without help.', 'Insight connects to existing operational databases and lets non-technical teams explore KPIs, build reports and share dashboards.

I built the data connectors, a caching layer for heavy queries and a clean, consistent UI so stakeholders can answer their own questions instead of waiting on ad-hoc reports.', 'Vue.js, Python, FastAPI, PostgreSQL, Alibaba Cloud', '', ''),
('Kumo Design System', 'UI/UX', '2023', 'UI/UX designer', 'image/works/kumo.svg', 'A calm, accessible component library and Figma kit shared across web and mobile products.', 'Kumo (雲, “cloud”) is a design system that brings consistency to a family of products. It includes design tokens for colour, type and spacing, 60+ accessible components and clear usage guidelines.

The Figma library and the coded components share the same tokens, so designers and developers always speak the same language, and new screens ship faster.', 'Figma, Design tokens, React, Storybook', '', ''),
('Helios — Solar Yield Monitor', 'IoT', '2025', 'Personal project', 'image/works/helios.svg', 'Tracks solar panel output against weather forecasts to spot underperforming panels early.', 'Helios is a side project born from my growing interest in renewable energy. An ESP32 measures the output of each panel string and compares it with the expected yield from weather forecasts.

When output drops below the forecast, for example because of dust, shading or a failing panel, Helios sends a notification with a clear explanation.', 'ESP32, MicroPython, InfluxDB, Next.js', '', '');

-- Insert Education Data
INSERT INTO education (graduation_year, institution, degree, description) VALUES
('Graduated 2017', 'Tokyo University of Technology', 'Bachelor of Computer Science', 'System Engineering'),
('Graduated 2012', 'College of Technology at Albaha', 'Diploma of Computer Technology', 'Computer Programming');

-- Insert Career Data
INSERT INTO career (date_range, company, position, location) VALUES
('May 2019 - July 2022', 'specialized by stc', 'IT Application Engineer (May 2019 - May 2021) | IT Application Specialist May (2021 - July 2022)', ''),
('July 2022 - Present', 'iotsquared', 'Senior Applications & Analytics Specialist', 'Riyadh, Saudi Arabia');

-- Insert Skills Data
INSERT INTO skills (name, percentage, description) VALUES
('Programming', 90, 'Dedicated software developer with over a decade of experience, starting in 2012 with Java-based Windows applications. Continuously committed to learning and adapting to new technologies, I have mastered modern frontend and backend frameworks, as well as cloud platforms such as Alibaba Cloud and Google Cloud. Skilled in DevOps practices, with hands-on experience building and optimizing CI/CD pipelines using Jenkins. Proven ability to deliver robust, scalable solutions across diverse tech stacks.'),
('UI/UX DESIGN', 95, 'Detail-oriented UI/UX designer with a strong focus on user-centered design principles. Adept at crafting intuitive, visually compelling interfaces that balance functionality with aesthetics. Experienced in translating user needs into seamless digital experiences through wireframing, prototyping, and usability testing. Passionate about staying current with design trends and emerging tools to drive innovation and enhance product usability.'),
('Microcontroller & Embedded Systems', 60, 'Proficient in embedded systems development with hands-on experience in FreeRTOS, Zephyr OS, and low-level programming for microcontrollers. Skilled in integrating hardware and software to enable efficient communication between embedded devices and connectivity modules. Solid understanding of real-time systems and IoT protocols, with a proven track record of delivering reliable, performance-driven embedded solutions.'),
('Renewable Energy (Emerging Interest)', 15, 'Currently expanding knowledge in renewable energy technologies, with foundational experience in green hydrogen generation and solar power systems. Actively pursuing opportunities to contribute to sustainable energy projects and grow expertise in the field.');

-- Insert Language Skills Data
INSERT INTO languages (name, percentage) VALUES
('Japanese LANGUAGE', 90),
('ENGLISH LANGUAGE', 65);
